version: '3.7'

services:

  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./www/build:/srv
    depends_on:
      - node-api
      - react-app

  node-api:
    build: 
      context: ./api
      args:
        NODE_ENV: production
    image: nidza81/node-api-image-prod
    container_name: node-api
    ports: 
      - "4000:4000"
    command: "npm start"

  react-app:
    stdin_open: true
    tty: true
    build: 
      context: ./www
      dockerfile: ./Dockerfile.prod

    image: nidza81/react-app-image-prod
    container_name: react-app-prod
    ports: 
      - "3000:3000"
    
    #environment:
    #  - CHOKIDAR_USEPOLLING=true
      #- NODE_ENV=development

  